FROM mcr.microsoft.com/windows:1809

LABEL name="Cygwin Container"
LABEL description="This container is a Windows container designed to use Cygwin's Bash shell by default. You can install the package using apt-cyg."
LABEL maintainer="Jung Hyun Nam <rkttu@rkttu.com>"

RUN @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
RUN choco install -y cygwin mingw

RUN curl https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg -o apt-cyg
RUN /tools/cygwin/bin/install apt-cyg /bin
RUN del apt-cyg

WORKDIR "/tools/cygwin"
RUN cygwinsetup.exe -q -P wget

WORKDIR "/tools/cygwin/bin"
SHELL ["bash.exe", "--login", "-i"]
CMD ["bash.exe", "--login", "-i"]