FROM rkttu/cygwin:3.0.4-1809-core

LABEL name="Cygwin Python 3 Container"
LABEL description="This container is a Cygwin based Python container designed to use Cygwin's Bash shell by default. You can install the package using apt-cyg."
LABEL maintainer="Jung Hyun Nam <rkttu@rkttu.com>"

RUN apt-cyg install python3 python3-devel python3-pip

SHELL ["/windows/system32/cmd.exe", "/c"]
RUN ["/tools/cygwin/bin/ash.exe", "/bin/rebaseall"]

CMD ["/tools/cygwin/bin/python3.6m.exe"]
SHELL ["/tools/cygwin/bin/python3.6m.exe"]